language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements/test.txt"
# # command to run tests
script: 
  - cd itblog
  - python manage.py test
